name: Build resume PDF
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: "cachix/install-nix-action@v17"
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build PDF
        run: "nix build"
      - name: Copy and stage the PDF
        run: |
          cp result/share/resume.pdf resume.pdf
          rm -r result
          git add resume.pdf
          git commit -m "Update resume.pdf"
          git push origin main
      - name: "Commit and push changes"
        uses: "ad-m/github-push-action@v0.6.0"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Update resume.pdf"
          branch: main
